add ephemeral_storage_container_volume_usage  metrics
jmcgrath207/k8s-ephemeral-storage-metrics pull request #87
Opened 2024-04-25 09:32 UTC by jicki

add `ephemeral_storage_container_volume_usage` 

the sample output 

```
ephemeral_storage_container_volume_usage{cluster="development-k8s-cluster",container="k8s-ephemeral-storage",endpoint="metrics",exported_container="postgresql",instance="172.18.23.200:9100",job="prometheus-ephemeral-storage-exporter",mount_path="/dev/shm",namespace="monitor-system",node_name="10-9-9-46.vm",pod="prometheus-ephemeral-storage-exporter-86dcfd97d9-wd79f",pod_name="postgresql-0",pod_namespace="demo-postgresql",prometheus="monitor-system/victoria-metrics-cluster",service="prometheus-ephemeral-storage-exporter",volume_name="dshm"} 210,870,272
```

2024-04-25 21:33 UTC, jmcgrath207 requested changes
Overall looks great. Once you get this CI test passing, I can handle the helm and e2e test for it.

2024-04-25 21:33 UTC, jmcgrath207 commented on pkg/pod/k8s.go
> +	if cr.containerVolumeUsage && cr.containerVolumeLimitsPercentage && p.Spec.Volumes != nil {
Lets do a `or` here. ex. `( cr.containerVolumeUsage || cr.containerVolumeLimitsPercentage)`

2024-04-26 01:39 UTC, jicki commented on pkg/pod/k8s.go
> +	if cr.containerVolumeUsage && cr.containerVolumeLimitsPercentage && p.Spec.Volumes != nil {
Update

2024-04-26 02:47 UTC, jmcgrath207 approved these changes

2024-04-26 03:28 UTC, merged

2024-04-26 04:21 UTC, jmcgrath207 commented
Thank you for your contribution @jicki, you change is now live in [1.9.0](https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/releases/tag/1.9.0)